model: CRNN

# load / save config
resume_iteration: 0
valid_interval: 500

# feature config
feature_type: melspec
sample_rate: 16000
# n_fft: 1024
win_length: 1024
hop_length: 320
fmin: 0
fmax: 8000
n_mels: 66
n_mfcc: 20

# dataset config
dataset:
  train:
    - TIMIT
  valid:
    - TIMIT
  test:
    - TIMIT
num_lbl: 61

# model config
batch_size: 16
num_frames: 168
model_complexity: 64

# trainer config
max_iteration: 1000000
learning_rate: 0.000018268946096351353
lr_decay_step: 853
lr_decay_rate: 0.98

# early stop config
patience: 5
es_criteria: f1_micro
goal: maximize
delta: 0